name: "Validate PR title"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  action-semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
